# Generated by Django 3.2.3 on 2021-06-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20)),
                ('complete', models.BooleanField()),
                ('level', models.CharField(choices=[('i', 'important'), ('u', 'unimportant')], default='u', max_length=1)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
